### ISSUE TITLE
Nodes are needed! Post your nodes in comments

### ISSUE THREAD

**Issue by litecoinz-project** [litecoinz-project/litecoinz#1]
Run your [LitecoinZ](https://github.com/litecoinz-project/litecoinz) and post your nodes here.

Full node test (open 29333 port TCP):
```
telnet dnsseed.kemperink.org 29333
```

**Comment by litecoinz-project** [comment]
PLEASE DO NOT ADD NODES YET! WE ARE STILL DEVELOPING IT, SO WE COULD RECREATE THE CHAIN AT ANY TIME. WE HOPE TO LAUNCH LITECOINZ BEFORE XMAS.

STAY TUNED!

**Comment by PsyTeck** [comment]
addnode=88.86.186.158:29333
addnode=178.32.117.60:29333
addnode=85.214.53.137:29333
addnode=139.59.145.115:29333
addnode=173.249.11.207:29333

**Comment by litecoinz-project** [comment]
thanks

**Comment by eocwizard** [comment]
addnode=71.193.55.64:29333

**Comment by micmac01** [comment]
addnode=82.236.69.249:29333

**Comment by minepool-ch** [comment]
addnode=81.29.192.216

**Comment by abakus1** [comment]
193.25.1.204:29333

**Comment by asterisk79** [comment]
addnode=173.212.236.200:29333

**Comment by ztraffic** [comment]
addnode=24.179.112.4:29333

**Comment by alexeysokol128** [comment]
addnode=31.173.82.177
