### ISSUE TITLE
MacOS error: call to 'Serialize' is ambiguous

### ISSUE THREAD

**Issue by ForTozs** [litecoinz-project/litecoinz#10]
### Describe the issue
I'm getting a build error:

```
 gcc -I. -g -O2 -Wall -Wextra -Wno-unused-function -c src/gen_context.c -o gen_context.o
   CXX      litecoinzd-litecoinzd.o
   CXX      libbitcoin_server_a-sendalert.o
   CXX      libbitcoin_server_a-addrman.o
 gcc gen_context.o -o gen_context
 ./gen_context
   CC       src/libsecp256k1_la-secp256k1.lo
 In file included from sendalert.cpp:41:
 In file included from ./main.h:14:
 In file included from ./amount.h:10:
 ./serialize.h:653:9: error: call to 'Serialize' is ambiguous
         ::Serialize(os, (*vi), nType, nVersion);
         ^~~~~~~~~~~
 ./serialize.h:659:5: note: in instantiation of function template specialization 'Serialize_impl<CSizeComputer, bool, std::__1::allocator<bool>, bool>' requested here
     Serialize_impl(os, v, nType, nVersion, T());
     ^
```

Lines 648–654 in src/serialize.h show:

```
template<typename Stream, typename T, typename A, typename V>
void Serialize_impl(Stream& os, const std::vector<T, A>& v, int nType, int nVersion, const V&)
{
    WriteCompactSize(os, v.size());
    for (typename std::vector<T, A>::const_iterator vi = v.begin(); vi != v.end(); ++vi)
        ::Serialize(os, (*vi), nType, nVersion);
}
```

Any ideas on how to fix this?

### Can you reliably reproduce the issue?
Yes.

#### If so, please list the steps to reproduce below:
1. Try to build LitecoinZ on a Mac.

### Expected behaviour
It should build perfectly, without any problems whatsoever, always.

### Actual behaviour
What always happens when I try to build things from source.

### What version of LitecoinZ are you using?
1.0.14

### Machine specs:
- OS: MacOS 10.13.3
- CPU: Skylake i5
- RAM: 16 GB
- Disk size: 500 GB
- Disk Type (HD/SDD): SSD

**Comment by litecoinz-project** [comment]
Hi! Thanks for your feedback. Please check the new release. 
https://github.com/litecoinz-project/litecoinz/archive/v1.0.15.zip

**Comment by litecoinz-project** [comment]
any news?

**Comment by litecoinz-project** [comment]
I've just compiled successfully the new wallet on macos! In few days I will commit changes on github and post the installation package.
