### ISSUE TITLE
Failure to build

### ISSUE THREAD

**Issue by egyptianbman** [litecoinz-project/litecoinz#11]
This issue tracker is only for technical issues related to LitecoinZ.

#### If so, please list the steps to reproduce below:
1.Trying to build with ./zcutil/build.sh -j$(nproc)

### Expected behaviour
Successful build

### Actual behaviour
```
libtool: Version mismatch error.  This is libtool 2.4.6 Debian-2.4.6-0.1, but the
libtool: definition of this LT_INIT comes from libtool 2.4.2.
libtool: You should recreate aclocal.m4 with macros from libtool 2.4.6 Debian-2.4.6-0.1
libtool: and run autoconf again.
libtool: Version mismatch error.  This is libtool 2.4.6 Debian-2.4.6-0.1, but the
libtool: definition of this LT_INIT comes from libtool 2.4.2.
libtool: You should recreate aclocal.m4 with macros from libtool 2.4.6 Debian-2.4.6-0.1
libtool: and run autoconf again.
make[3]: *** [qrencode.lo] Error 63
```

### Screenshots.
![image](https://user-images.githubusercontent.com/323600/37010852-20d867b4-20b3-11e8-8eae-9f5cce5a79c1.png)

### What version of LitecoinZ are you using?
latest from github (master branch)

### Machine specs:
- OS: centos:latest
- CPU: Intel(R) Core(TM) i7-7800X CPU @ 3.50GHz
- RAM: 128GB
- Disk size: 1TB
- Disk Type (HD/SDD): SSD

**Comment by litecoinz-project** [comment]
Hi! I'm pushing right now the new release. Please hold on.

**Comment by litecoinz-project** [comment]
Hi! To fix this issue, please download last release and before building modify the file 'depends/packages/qrencode.mk' like this:

```
package=qrencode
$(package)_version=4.0.0
$(package)_download_path=https://fukuchi.org/works/qrencode/
$(package)_file_name=$(package)-$($(package)_version).tar.bz2
$(package)_sha256_hash=c90035e16921117d4086a7fdee65aab85be32beb4a376f6b664b8a425d327d0b

define $(package)_preprocess_cmds
  $($(package)_autoreconf
endef

define $(package)_set_vars
$(package)_config_opts=--disable-shared -without-tools --disable-sdltest
$(package)_config_opts_linux=--with-pic
endef

define $(package)_config_cmds
  $($(package)_autoconf)
endef

define $(package)_build_cmds
  $(MAKE)
endef

define $(package)_stage_cmds
  $(MAKE) DESTDIR=$($(package)_staging_dir) install
endef
```

A pull request will address this issue very soon!

**Comment by egyptianbman** [comment]
Man, I need to get better at tracking things like this down. That did the trick, thank you!
