### ISSUE TITLE
Wallet Installation Issue in Windows 10

### ISSUE THREAD

**Issue by calql8tor** [litecoinz-project/litecoinz#13]
This error is appearing during the installation process not allowing the process to complete.

LitecoinZ - Error

Cannot find the LitecoinZ network parameters in the following directory:
"C:\Users\Name\AppData\Roaming\LitecoinZParams"
Please run './zcutil/fetch-params.sh' and then restart.

Trying to run the software via menu returns:
Runaway exception
A fatal error occured. LitecoinZ can no longer continue safely and will quit.

### Machine specs:
- OS: Windows 10
- CPU: i7-6700 3.4GHz
- RAM: 16GB
- Disk size: 512GB
- Disk Type (HD/SDD): Samsung SSD 960 Pro

**Comment by yaddaa** [comment]
So any help from devs?

**Comment by litecoinz-project** [comment]
which version of the wallet are you running? did you install the new wallet from https://github.com/litecoinz-project/litecoinz/releases/download/v1.0.15/litecoinz-1.0.15-win64-setup.exe ?
if yes, just delete the "C:\Users\<Name>\AppData\Roaming\LitecoinZParams" and rerun the wallet. On first run it will download the LitecoinZParams. Just run and wait it finish to download it.

**Comment by yaddaa** [comment]
Doesn't works for me.
After delete the folder and run at first I have this issue:
Cannot find the LitecoinZ network parameters in the following directory:
"C:\Users\Name\AppData\Roaming\LitecoinZParams"
Please run './zcutil/fetch-params.sh' and then restart.

The second run have the same(

But the third run and all runs after I have: "A fatal error occurred. LitecoinZ can no longer continue safely and will quit"

<img width="805" alt="2018-03-14 13 38 22" src="https://user-images.githubusercontent.com/13570533/37400399-8106ba60-278d-11e8-959a-38b038691903.png">
<img width="810" alt="2018-03-14 13 39 03" src="https://user-images.githubusercontent.com/13570533/37400400-81276b2a-278d-11e8-836a-2e453613fd57.png">

**Comment by calql8tor** [comment]
I did have that version of the wallet.  Redownloaded from your link too.

I deleted the folder you mentioned and the issue still persists.

Watching LitecoinZParams - each attempt created another file till fatal erro on try 3.
Try 1. it created sprout-proving.key and failed
Try 2. it created spour-verifying.key
Try 3. A fatal error occurred. LitecoinZ can no longer continue safely and will quit

Tried removing the folder a few times.

calql8tor
________________________________

**Comment by yaddaa** [comment]
the same

**Comment by litecoinz-project** [comment]
1. Delete the content of the LitecoinZParams
2. Dowload file https://litecoinz.info/downloads/sprout.zip
3. Extract the content of the zip inside the LitecoinZParams folder. (Just the files, do not create sub-direcotories)
4. Start litecoinz-qt.exe

**Comment by gtx97** [comment]
It’s absolutely crap ..wallet does not work after trying all them options and also trying older versions ...if you can’t even get a wallet right then how are we meant to have faith unit

**Comment by litecoinz-project** [comment]
Dear @gtx97 ,
the wallet works fine on windows based pc of many users, but for few users does not work and for this reason it's not easy to understand what causes the problem. I'm investigating on this issue. One possible cause could be the CPU of the pc that does not support AVX2 code.

@yaddaa @calql8tor can you give me a feedback? Did you solve the problem? If not, could you send the debug.log file? Did you check also on windows event viewer? I need more info to investigate better, only tell that on your pc does not work is not enought.

Thanks

**Comment by gtx97** [comment]
I have the same errors as above comments (exactly the same) I have used my i3 laptop I have also tried it on my mining rig and also on a i5 setup all windows 10 softwear

**Comment by gtx97** [comment]
I have even tried the java swing wallet ...I have not had any issues like this before with any wallet and I have a few that are the exact same layout as the ltc Z wallet so I don’t believe it is a problem with any of my pcs / laptop

**Comment by litecoinz-project** [comment]
@gtx97 java swing wallet is not a real wallet. It is just a GUI that run on top of litecoinzd.exe that is the real Wallet, thus before running the java swing gui you must setup and execute the litecoinzd.exe daemon. To be sure that setup is correct, instead of double click on the exe, please open "cmd.exe" cd to the folder of litecoinz and run litecoinzd.exe so any output could be read.

As I said before I need more info to diagnostic this issue. Send here debug.log and windows event log regatding the crash of the daemon.

**Comment by litecoinz-project** [comment]
@gtx97 @yaddaa  @calql8tor 
Please, install this new release and let me know if it works, thanks
https://github.com/litecoinz-project/litecoinz-win/releases/download/v1.0.15.1/litecoinz-1.0.15.1-win64-setup.exe

**Comment by litecoinz-project** [comment]
Did you try this workaround?

Download https://litecoinz.info/downloads/sprout.zip and unzip (do not create subfolders) in C:\Users\%username%\AppData\Roaming\LitecoinZ

After open the wallet and let me know if it works.

**Comment by calql8tor** [comment]
Unfortunately the windows installer is not on the page to try right now.  Please advise when it is.

calql8tor
________________________________

**Comment by litecoinz-project** [comment]
sorry, try now https://github.com/litecoinz-project/litecoinz/releases/download/v1.0.15.1/litecoinz-1.0.15.1-win64-setup.exe

**Comment by litecoinz-project** [comment]
@gtx97 @calql8tor @yaddaa  did you upgrade to the last version? Can I close this issue?

**Comment by calql8tor** [comment]
Same issue

Sent from my iPhone

On Mar 18, 2018, at 12:03 PM, LiteCoinZ <notifications@github.com<mailto:notifications@github.com>> wrote:


@gtx97<https://github.com/gtx97> @calql8tor<https://github.com/calql8tor> @yaddaa<https://github.com/yaddaa> did you upgrade to the last version? Can I close this issue?

**Comment by litecoinz-project** [comment]
Send me more details of the error
OS?
LANG?
SCREENSHOTS?
WINDOWS EVENTS LOG?
DEBUG.LOG?
Thanks

**Comment by litecoinz-project** [comment]
no information provided

**Comment by calql8tor** [comment]
I deleted both directories (litecoinz/litecoinzparams) in roaming profile and reinstalled.  I thought it hung but at least wasn’t erroring out.  It came up in about 5 minutes and is now syncing with the network.

Looks like issue resolved…..

Thanks
calql8tor
