### ISSUE TITLE
startup error LitecoinZ 1.0.15

### ISSUE THREAD

**Issue by Imyrek** [litecoinz-project/litecoinz#18]
When starts  LitecoinZ 1.0.15 an error occurs

### Machine specs:
- OS:Windows 10
- CPU:i5-4200H
- RAM:12
- Disk size:500gb
- Disk Type (HD/SDD):hdd

![litacoinz error](https://user-images.githubusercontent.com/37457366/37544009-9042759e-2974-11e8-867b-b64be6a54dbd.jpg)

**Comment by Imyrek** [comment]
![litacoinz error](https://user-images.githubusercontent.com/37457366/37543952-5f34f6e8-2974-11e8-956f-fc03cd0785f5.jpg)

**Comment by litecoinz-project** [comment]
where did you download this version?

**Comment by Imyrek** [comment]
https://github.com/litecoinz-project/litecoinz/releases

**Comment by litecoinz-project** [comment]
ok! I'm just releasing the new version 1.0.15.1 in this weekend that solve the problem. Try to download manually the spparams file and put them in the LitecoinZParams folder.

Download https://litecoinz.info/downloads/sprout.zip and unzip (do not create subfolders) in C:\Users\%username%\AppData\Roaming\LitecoinZ

After open the wallet and let me know if it works.

**Comment by Imyrek** [comment]
all good
