### ISSUE TITLE
cannot compile after latest

### ISSUE THREAD

**Issue by sennevb** [litecoinz-project/litecoinz#19]
/wallets/litecoinz/src/alert.cpp:106: undefined reference to `GetAdjustedTime()'
libbitcoin_server.a(libbitcoin_server_a-alert.o): In function `LogPrint<int, bool>':
/wallets/litecoinz/src/util.h:98: undefined reference to `LogAcceptCategory(char const*)'
/wallets/litecoinz/src/util.h:98: undefined reference to `LogPrintStr(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
libbitcoin_server.a(libbitcoin_server_a-alert.o): In function `LogPrint<int>':
/wallets/litecoinz/src/util.h:98: undefined reference to `LogPrintStr(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/wallets/litecoinz/src/util.h:98: undefined reference to `LogAcceptCategory(char const*)'
/wallets/litecoinz/src/util.h:98: undefined reference to `LogPrintStr(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/wallets/litecoinz/src/util.h:98: undefined reference to `LogAcceptCategory(char const*)'
/wallets/litecoinz/src/util.h:98: undefined reference to `LogPrintStr(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
libbitcoin_server.a(libbitcoin_server_a-alert.o): In function `CAlert::IsInEffect() const':
/wallets/litecoinz/src/alert.cpp:106: undefined reference to `GetAdjustedTime()'
libbitcoin_server.a(libbitcoin_server_a-alert.o): In function `void CNode::PushMessage<CAlert>(char const*, CAlert const&)':
/wallets/litecoinz/src/net.h:487: undefined reference to `CNode::BeginMessage(char const*)'
/wallets/litecoinz/src/net.h:489: undefined reference to `CNode::EndMessage()'
libbitcoin_server.a(libbitcoin_server_a-alert.o): In function `CAlert::RelayTo(CNode*) const':
/wallets/litecoinz/src/alert.cpp:141: undefined reference to `GetAdjustedTime()'
libbitcoin_server.a(libbitcoin_server_a-alert.o): In function `void CNode::PushMessage<CAlert>(char const*, CAlert const&)':
/wallets/litecoinz/src/net.h:493: undefined reference to `CNode::AbortMessage()'
libbitcoin_server.a(libbitcoin_server_a-bloom.o): In function `CBloomFilter::IsRelevantAndUpdate(CTransaction const&)':
/wallets/litecoinz/src/bloom.cpp:173: undefined reference to `Solver(CScript const&, txnouttype&, std::vector<std::vector<unsigned char, std::allocator<unsigned char> >, std::allocator<std::vector<unsigned char, std::allocator<unsigned char> > > >&)'
libbitcoin_common.a(libbitcoin_common_a-base58.o): In function `CBitcoinAddress::IsValid() const':
/wallets/litecoinz/src/base58.cpp:244: undefined reference to `Params()'
/wallets/litecoinz/src/base58.cpp:244: undefined reference to `Params()'
libbitcoin_common.a(libbitcoin_common_a-base58.o): In function `CBitcoinAddress::Get() const':
/wallets/litecoinz/src/base58.cpp:271: undefined reference to `Params()'
/wallets/litecoinz/src/base58.cpp:273: undefined reference to `Params()'
libbitcoin_common.a(libbitcoin_common_a-base58.o): In function `CBitcoinAddress::IsValid() const':
/wallets/litecoinz/src/base58.cpp:244: undefined reference to `Params()'
libbitcoin_common.a(libbitcoin_common_a-base58.o):/root/wallets/litecoinz/src/base58.cpp:281: more undefined references to `Params()' follow
libbitcoin_common.a(libbitcoin_common_a-block.o): In function `CBlock::ToString[abi:cxx11]() const':
/wallets/litecoinz/src/primitives/block.cpp:126: undefined reference to `CTransaction::ToString[abi:cxx11]() const'
collect2: error: ld returned 1 exit status
Makefile:3606: recipe for target 'litecoinzd' failed
make[2]: *** [litecoinzd] Error 1
make[2]: Leaving directory '/wallets/litecoinz/src'
Makefile:8971: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/wallets/litecoinz/src'
Makefile:712: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

### What version of LitecoinZ are you using?
latest git pull

### Machine specs:
- OS: ubuntu 16.04
- CPU: Dual xeon
- RAM: 64GB

**Comment by litecoinz-project** [comment]
Please check if all dependencies are installed before compiling. If you still have this issue, please attach here a text file with all compilation output (from git clone to the end)

**Comment by sennevb** [comment]
All dependencies are installed! I Will post a file in a few hours

**Comment by sennevb** [comment]
Yes exactly

**Comment by litecoinz-project** [comment]
I compiled on Ubuntu without any issue. Please give me more details about your compilation steps:

Correct steps are:
1) sudo apt-get install       build-essential pkg-config libc6-dev m4 g++-multilib       autoconf libtool ncurses-dev unzip git python       zlib1g-dev wget bsdmainutils automake
2) git clone https://github.com/litecoinz-project/litecoinz.git
3) cd litecoinz
4) ./zcutil/build.sh

**Comment by sennevb** [comment]
i did a fresh pull
and recompiled, now it seems to work
weird..
