### ISSUE TITLE
Pools are needed! Post pools in comments

### ISSUE THREAD

**Issue by litecoinz-project** [litecoinz-project/litecoinz#2]
Post mining pools here.

**Comment by sssergy** [comment]
http://46.105.90.177/getting_started 1.5% fee

**Comment by litecoinz-project** [comment]
Thank you!
Please disable it for few weeks because my project is still under development and it's not yet released. 

I will post a message here when it's ready for a global launch.

CU soon

**Comment by sssergy** [comment]
This pool is also for the test. I have not run on this algorithm yet. There were errors during the assembly. If you need to test, please contact.14.12.2017, 00:46, "LiteCoinZ" <notifications@github.com>:Thank you!
Please disable it for few weeks because my project is still under development and it's not yet released.
I will post a message here when it's ready for a global launch.
CU soon

**Comment by gtrrkicw** [comment]
LTZ Mining Pool - http://crushr.io

**Comment by minepool-ch** [comment]
MINEPOOL.CH - http://ltz.minepool.ch
![minepool_logo](https://user-images.githubusercontent.com/35145748/35182403-7174e5be-fdd4-11e7-84bf-ea0049f43f29.png)

**Comment by abakus1** [comment]
www.abakus.gemini.net.pl 
![logo](https://user-images.githubusercontent.com/32597642/35213375-afd57d0c-ff5d-11e7-8c3c-f1e45de1fd6a.png)

**Comment by ztraffic** [comment]
New LitecoinZ mining pool !!  - [http://z-traffic-pool.eu]

ZClassic AMD GPU Config Miner:
ZecMiner64.exe -zpool z-traffic-pool.eu:3042 -zwal <wallet>.rigname -zpsw x -allpools 1

ZClassic GTX NVIDIA GPU Config Miner:
miner --server z-traffic-pool.eu --user <wallet> --pass x --port 3042

**Comment by nettogroft** [comment]
https://zpool.wfmpools.com

We have other zcoins up there right now.. litecoinz being the newest one as of tonight. 
cluster.zpool.wfmpools.com is the stratum host and the port number is 3082. 
We have a stratum on the east coast of the US as well as the west coast.

Ex: miner --server cluster.zpool.wfmpools.com --port 3082 --user L1B3L5q82svXwXoMC2eSsLDtaQuiVkC95YV.nett --pass x --pec --intensity 50

**Comment by appkoders** [comment]
New LiteCoinZ mining pool: https://ltz.leafpool.com/

**Comment by insound** [comment]
We add LitecoinZ coin to https://litecoinz.axepool.com/. EU Dedicated, TCP tuning for miners and redhat based OS - best performance.

**Comment by magnafic0** [comment]
EZPOOL.GA new LTZ pool at http://www.ezpool.ga/

![image](https://user-images.githubusercontent.com/26013064/38380823-e6996976-38d2-11e8-8a93-fca05bec7d37.png)

ZecMiner64.exe
-zpool stratum+tcp://ezpool.ga:3395
-zwal LxxxLTZWalletAddressxxxxxxxxxxxxxxx.1RigName
-zpsw x
-i 8
-a 0
-asm 1
-allpools 1

for NVIDIA just use ezpool.ga:3395
