### ISSUE TITLE
This version will be deprecated at block height 97447, and will automatically shut down. You should upgrade to the latest version of LitecoinZ.

### ISSUE THREAD

**Issue by dEROZA** [litecoinz-project/litecoinz#21]
This issue tracker is only for technical issues related to LitecoinZ.

### Expected behaviour
software must be have autoupdate module

### Actual behaviour
program works, but I not understand is it works correctly without supporting of this block

### Screenshots.
![image](https://user-images.githubusercontent.com/8126176/41501500-26fed4f4-71d8-11e8-8e58-ee304ef5960d.png)

### What version of LitecoinZ are you using?
LitecoinZ version v1.0.15-f27d3e1 (64-bit)

### Machine specs:
- OS: ubuntu 16.04 x64
- CPU: fx8350
- RAM: r7 amd
- Disk size: 128
- Disk Type SDD: kingston

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by litecoinz-project** [comment]
This message does not indicate a problem, but only an alert to remind users to install the latest version of LitecoinZ available.
