### ISSUE TITLE
Pull Request Usage Request

### ISSUE THREAD

**Issue by egyptianbman** [litecoinz-project/litecoinz#23]
Can you use Pull requests when pushing updates? The reason for this is pool maintainers like myself rely on Github's "watch" feature which sends me an e-mail any time pull requests are created, updated, merged, etc.

When you push up a commit, it's silent and there's no notification to pool maintainers (or anyone else who is watching, exchanges, calculators, etc).

In addition, I see an updated was posted on Discord but it didn't have @everyone so it was a silent notification -- for an update that is critical; thanks.

**Comment by LitecoinZ** [comment]
ok I will do it
