### ISSUE TITLE
How to solve "0 nodes connected" or "sync stuck at height 189999"

### ISSUE THREAD

**Issue by MarkLTZ** [litecoinz-project/litecoinz#29]
If you have one of these problems, please add the following node to solve it:

35.196.171.77
35.231.216.251
94.237.50.117
35.231.142.184
173.212.253.221 
81.187.84.193 
111.90.148.99 
89.252.203.250
76.65.147.80 
18.197.48.53 
95.216.116.61
52.15.220.131
3.8.75.233
93.114.73.8
5.3.120.225
75.97.223.8
85.15.176.1
3.122.99.135
89.25.89.194
136.33.111.57
162.232.249.191
93.42.71.164
212.186.33.166

**Comment by skironDotNet** [comment]
put this into your litecoinz.conf file

addnode=equipool.1ds.us
addnode=35.196.171.77

**Comment by LitecoinZ** [comment]
addnode 35.196.171.77 add
addnode 35.231.142.184 add
addnode 173.212.253.221 add 
addnode 81.187.84.193 add 
addnode 111.90.148.99 add 
addnode 89.252.203.250 add
addnode 76.65.147.80 add 
addnode 18.197.48.53 add 
addnode 95.216.116.61 add
addnode 94.237.50.117 add
addnode 52.15.220.131 add
addnode 3.8.75.233 add
addnode 93.114.73.8 add
addnode 5.3.120.225 add
addnode 75.97.223.8 add
addnode 85.15.176.1 add
addnode 3.122.99.135 add
addnode 89.25.89.194 add
addnode 136.33.111.57 add
addnode 162.232.249.191 add
addnode 93.42.71.164 add
addnode 212.186.33.166 add
