### ISSUE TITLE
Seed nodes are needed! Post your Seed nodes in comments

### ISSUE THREAD

**Issue by litecoinz-project** [litecoinz-project/litecoinz#3]
Run your [LitecoinZ seeder](https://github.com/litecoinz-project/litecoinz-seeder) and post your DNS here.

Seed nodes will be added to [LitecoinZ](https://github.com/litecoinz-project/litecoinz) source code.

The requirement is to have full node running & seeder at the same machine.
Test your seeder from other machine. It should get the same output as test to current seeders.

Full node test (open 29333 port TCP):
```
telnet dnsseed.kemperink.org 29333
```
Seeder test (Open port 53 UDP):
```
nslookup dnseed.litecoinz.info dnseed.litecoinz.info
```

**Comment by litecoinz-project** [comment]
PLEASE DO NOT SEED NODES YET! WE ARE STILL DEVELOPING IT, SO WE COULD RECREATE THE CHAIN AT ANY TIME. WE HOPE TO LAUNCH LITECOINZ BEFORE XMAS.

STAY TUNED!

**Comment by PsyTeck** [comment]
addnode=88.86.186.158:29333
addnode=178.32.117.60:29333
addnode=85.214.53.137:29333
addnode=139.59.145.115:29333
addnode=173.249.11.207:29333
