### ISSUE TITLE
"Accounts not supported" ???

### ISSUE THREAD

**Issue by skironDotNet** [litecoinz-project/litecoinz#31]
You need to fix 'help' page or add account support because they are partially supported, for example 'listaccounts' works

calling 'help'

![ltz2](https://user-images.githubusercontent.com/2981715/50097865-6b89b600-01e0-11e9-8a13-a27d64a841ec.png)

calling 'listaccounts' and  'getbalance'

![ltz1](https://user-images.githubusercontent.com/2981715/50098070-d76c1e80-01e0-11e9-98b5-d9bed09b24b0.png)

**Comment by skironDotNet** [comment]
I found this https://forum.zcashcommunity.com/t/why-are-the-account-rpc-commands-unsupported/3153

But since the one can set the label to the address in the UI, why RPC can't that would be me question to the whole crypto community not only you. And I know your wallet behavior is just a result of a fork from parent (ZCash in this case)

**Comment by LitecoinZ** [comment]
Fixed on dev branch. Asap on master.
