### ISSUE TITLE
build from source

### ISSUE THREAD

**Issue by bshowket** [litecoinz-project/litecoinz#7]
trying to build in ubuntu 16.04 , getting this error

> This program built for x86_64-pc-linux-gnu

**Comment by litecoinz-project** [comment]
Hello there,

could you copy here the entire build output?

Thanks

**Comment by bshowket** [comment]
`xxxxxx:~/litecoinz$ ./zcutil/build.sh --disable-rust -j$(1)
1: command not found
+ LCOV_ARG=
+ HARDENING_ARG=--enable-hardening
+ TEST_ARG=
+ '[' x--disable-rust = x--enable-lcov ']'
+ '[' x--disable-rust = x--disable-tests ']'
+ MINING_ARG=
+ '[' x--disable-rust = x--disable-mining ']'
+ PROTON_ARG=--enable-proton=no
+ '[' x--disable-rust = x--enable-proton ']'
+ LIBS_ARG=
+ '[' x--disable-rust = x--disable-libs ']'
+ BUILD_OPT=
+ '[' x86_64-unknown-linux-gnu = x86_64-pc-mingw64 ']'
++ pwd
+ PREFIX=/home/joy/litecoinz/depends/x86_64-unknown-linux-gnu/
+ eval make --version
++ make --version
GNU Make 4.1
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2014 Free Software Foundation, Inc.
Licence GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
+ eval gcc --version
++ gcc --version
gcc (Ubuntu 5.4.1-2ubuntu1~16.04) 5.4.1 20160904
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

+ eval g++ --version
++ g++ --version
g++ (Ubuntu 5.4.1-2ubuntu1~16.04) 5.4.1 20160904
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

+ as --version
GNU assembler (GNU Binutils for Ubuntu) 2.26.1
Copyright (C) 2015 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or later.
This program has absolutely no warranty.
This assembler was configured for a target of `x86_64-linux-gnu'.
+ ld -v
GNU ld (GNU Binutils for Ubuntu) 2.26.1
+ HOST=x86_64-unknown-linux-gnu
+ BUILD=x86_64-unknown-linux-gnu
+ NO_PROTON=--enable-proton=no
+ make --disable-rust -j -C ./depends/ V=1
make: unrecognised option '--disable-rust'
Usage: make [options] [target] ...
Options:
  -b, -m Ignored for compatibility.
  -B, --always-make Unconditionally make all targets.
  -C DIRECTORY, --directory=DIRECTORY
                              Change to DIRECTORY before doing anything.
  -d Print lots of debugging information.
  --debug[=FLAGS] Print various types of debugging information.
  -e, --environment-overrides
                              Environment variables override makefiles.
  --eval=STRING               Evaluate STRING as a makefile statement.
  -f FILE, --file=FILE, --makefile=FILE

                              Read FILE as a makefile.

  -h, --help Print this message and exit.
  -i, --ignore-errors         Ignore errors from recipes.
  -I DIRECTORY, --include-dir=DIRECTORY
                              Search DIRECTORY for included makefiles.
  -j [N], --jobs[=N] Allow N jobs at once; infinite jobs with no arg.
  -k, --keep-going Keep going when some targets can't be made.
  -l [N], --load-average[=N], --max-load[=N]
                              Don't start multiple jobs unless load is below N.
  -L, --check-symlink-times Use the latest mtime between symlinks and target.
  -n, --just-print, --dry-run, --recon
                              Don't actually run any recipe; just print them.
  -o FILE, --old-file=FILE, --assume-old=FILE
                              Consider FILE to be very old and don't remake it.
  -O[TYPE], --output-sync[=TYPE]
                              Synchronize output of parallel jobs by TYPE.
  -p, --print-data-base Print make's internal database.
  -q, --question              Run no recipe; exit status says if up to date.
  -r, --no-builtin-rules Disable the built-in implicit rules.
  -R, --no-builtin-variables Disable the built-in variable settings.
  -s, --silent, --quiet       Don't echo recipes.
  -S, --no-keep-going, --stop
                              Turns off -k.
  -t, --touch Touch targets instead of remaking them.
  --trace                     Print tracing information.
  -v, --version Print the version number of make and exit.
  -w, --print-directory Print the current directory.
  --no-print-directory Turn off -w, even if it was turned on implicitly.
  -W FILE, --what-if=FILE, --new-file=FILE, --assume-new=FILE
                              Consider FILE to be infinitely new.
  --warn-undefined-variables Warn when an undefined variable is referenced.

This program built for x86_64-pc-linux-gnu
Report bugs to <bug-make@gnu.org>
`

**Comment by litecoinz-project** [comment]
There is a doc bug in the README.md,

please run again the build.sh without "--disable-rust"

Rust code was already cutted off from LitecoinZ

We apoligize for this issue.

**Comment by bshowket** [comment]
Perfect!! its building now...

**Comment by bshowket** [comment]
I am having parsing issue now with z-nomp pull,

> 2018-01-16 22:39:03 [Payments]  [litecoinz] Could not parse rpc data from daemon instance  0

**Comment by litecoinz-project** [comment]
I think it's a z-nomp related issue.

**Comment by litecoinz-project** [comment]
We soft close this issue. Open a new one if you need our help.
The LitecoinZ developers
